
system:
  num_workers: 8
  gpus:
    strategy: auto
    num_devices: 1
    accelerator: mps

dataset:
  type: 0
  binarize: 1
  save: 0
  augmentations: 0

paths:
  data: /Users/june/Documents/data 

algorithm:
  n_pca: 10

network:
  arch: 0
  optimizer: 1
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.01

models:
  train: 1
  choices: [0, 1, 2]
