
system:
  num_workers: 8
  gpus:
    strategy: auto
    num_devices: 1
    accelerator: mps

dataset:
  type: 1
  save: 0
  augmentations: 1


paths:
  data: /Users/june/Documents/data 


network:
  arch: 0
  optimizer: 1
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.01
