

elements:
  mean:
    #- [0,0]
    #- [0,0]
    - [6,2]
    - [2,6]
  covariance:
    #- [[1.0, 0.0],[0.0, 0.1]]
    #- [[1.0, 0.0],[0.0, 0.1]]
    - [[2.1, 1.5],[1.5, 3.8]]
    - [[4.1, 0.4],[0.4, 2.8]]
  prior:
    - [0.5]
    - [0.5]


datasets:
  num_classes: 2
  num_samples: 1000
  num_features: 2
  show: 0




