
paths:
  results: /Users/june/Documents/results/RNNvsLSTM

arch:
  batch_size:
  learning_rate:
  num_epochs:

model:
  """
  model type 0 for RNN
             1 for LSTM
  """
  model_type:
  input_size:
  output_size:
  hidden_size:
  num_layers:
  
