
system:
  num_workers: 1
  gpus:
    strategy: auto
    num_devices: 1
    accelerator: cpu

paths:
  data: /Users/june/Documents/data/CNT
  results:
    LSTM: /Users/june/Documents/results/RNNvsLSTM/LSTM
    RNN: /Users/june/Documents/results/RNNvsLSTM/RNN


dataset:
  input_seq: 5
  output_seq: 3
  resize: 0.1

arch:
  batch_size: 1
  learning_rate: 0.005
  num_epochs: 50
  teacher_forcing: 0

model:
  # 1 for LSTM 0 for RNN
  model_type: 1
  input_size: 160000
  hidden_size: 64
  output_size: 160000
  num_layers: 3
  


