
system:
  num_workers: 1
  gpus:
    strategy: auto
    num_devices: 1
    accelerator: cpu

paths:
  data: /Users/june/Documents/data/CNT
  results:
    LSTM: /Users/june/Documents/results/RNNvsLSTM/LSTM
    CNN_LSTM: /Users/june/Documents/results/RNNvsLSTM/CNN_LSTM
    dense_CNN_LSTM: /Users/june/Documents/results/RNNvsLSTM/dens_CNN_LSTM

dataset:
  input_seq: 5
  output_seq: 2
  resize: 0.1

arch:
  batch_size: 1
  learning_rate: 0.005
  num_epochs: 50
  teacher_forcing: 0

model:
  # 1 for LSTM 0 for RNN
  model_type: 3
  input_size: 160000
  hidden_size: 32
  output_size: 160000
  num_layers: 3
  


